@echo off
cd /d "C:\Users\alexj\Projects\MLB Daily Results"

echo =========================================================
echo  Push code changes to GitHub
echo  (HTML will be regenerated by the GitHub Actions run)
echo =========================================================
echo.

REM Clear any stale .git\index.lock left over from a prior aborted operation
REM (e.g. an earlier git process crashed or was killed mid-command).
if exist ".git\index.lock" (
    echo Clearing stale .git\index.lock...
    del /f /q ".git\index.lock"
)

REM Discard any stale local HTML regen — GHA is the source of truth for it.
REM Without this, a stale local mlb_daily_stats.html will conflict on every
REM rebase against the GHA-committed version.
git checkout HEAD -- mlb_daily_stats.html 2>nul

REM Stage only code files — NOT mlb_daily_stats.html. GHA regenerates that.
echo [1/3] Staging code changes...
git add fetch_mlb_stats.py fantasy.py parse_espn_rosters.py lineup_optimizer.py ^
        player_cards.py html_template.py data_fetch.py config.py utils.py ^
        pitching_leaderboard.py batting_leaderboard.py requirements.txt ^
        push_update.bat espn_rosters.json ^
        .github\workflows\daily.yml 2>nul

REM Pick up Standings-tab image assets (mickey.*) if present.
REM Guarded with `if exist` so missing files don't error out the script.
for %%F in (mickey.png mickey.jpg mickey.jpeg mickey.webp mickey.gif) do (
    if exist "%%F" git add "%%F"
)

git diff --cached --quiet
if %errorlevel% equ 0 (
    echo   No staged changes to commit.
    set NOTHING_STAGED=1
) else (
    echo [2/3] Committing...
    git commit -m "Update scripts"
    if errorlevel 1 (
        echo ERROR: commit failed.
        pause
        exit /b 1
    )
)

echo [3/3] Syncing with remote and pushing...
REM Stash anything that wasn't staged (e.g. regenerated HTML, temp files)
REM so pull --rebase has a clean tree. Remote almost always has new GHA
REM commits, so --rebase is required.
git stash --include-untracked >nul 2>&1
git pull --rebase
if errorlevel 1 (
    echo.
    echo Rebase hit a conflict. Resolve it, then run:
    echo    git rebase --continue
    echo    git stash pop
    echo    git push
    pause
    exit /b 1
)
git stash pop >nul 2>&1
git push
if errorlevel 1 (
    echo ERROR: push failed.
    pause
    exit /b 1
)

echo.
echo =========================================================
echo  Code pushed. Now trigger a GitHub Actions run to rebuild
echo  the dashboard HTML:
echo.
echo    1. Open https://github.com/alexjmartin100-pixel/mlb-daily-stats/actions
echo    2. Click "MLB Stats Daily Update" in the left sidebar
echo    3. Click the "Run workflow" dropdown on the right
echo    4. Click the green "Run workflow" button
echo.
echo  Takes ~7 minutes, then live site updates ~2 min after:
echo  https://mlb-stats-ae429.web.app/mlb_daily_stats.html
echo =========================================================
pause
