@echo off
cd /d "C:\Users\alexj\Projects\MLB Daily Results"

echo =========================================================
echo  Push dashboard perf fix to GitHub
echo  (externalizes ~13 MB headshot blob to pc_photos.js)
echo  HTML + pc_photos.js will be regenerated by the GHA run.
echo =========================================================
echo.

REM Clear any stale .git\index.lock left over from a prior aborted operation.
if exist ".git\index.lock" (
    echo Clearing stale .git\index.lock...
    del /f /q ".git\index.lock"
)

REM Discard any stale local HTML regen — GHA is the source of truth for it.
git checkout HEAD -- mlb_daily_stats.html 2>nul

echo [1/3] Staging player_cards.py + push_perf_fix.bat...
git add player_cards.py push_perf_fix.bat

git diff --cached --quiet
if %errorlevel% equ 0 (
    echo   No staged changes to commit.
) else (
    echo [2/3] Committing...
    git commit -m "Externalize headshot blob to pc_photos.js, drop search onkeyup duplicate"
    if errorlevel 1 (
        echo ERROR: commit failed.
        pause
        exit /b 1
    )
)

echo [3/3] Syncing with remote and pushing...
REM Remote almost always has new GHA "Daily stats update" commits, so we
REM stash any working-tree leftovers + rebase before pushing.
git stash --include-untracked >nul 2>&1
git pull --rebase
if errorlevel 1 (
    echo.
    echo Rebase hit a conflict. Resolve it, then run:
    echo    git rebase --continue
    echo    git stash pop
    echo    git push
    pause
    exit /b 1
)
git stash pop >nul 2>&1
git push
if errorlevel 1 (
    echo ERROR: push failed.
    pause
    exit /b 1
)

echo.
echo =========================================================
echo  Code pushed. Trigger a GitHub Actions run to rebuild the
echo  dashboard so you see the perf improvement immediately:
echo.
echo    1. Open https://github.com/alexjmartin100-pixel/mlb-daily-stats/actions
echo    2. Click "MLB Stats Daily Update" in the left sidebar
echo    3. Click the "Run workflow" dropdown on the right
echo    4. Click the green "Run workflow" button
echo.
echo  Takes ~7 minutes. After that, live site loads ~3x faster:
echo  https://mlb-stats-ae429.web.app/mlb_daily_stats.html
echo =========================================================
pause
